###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
#                                                                             #
# This software is distributed under the terms of the Apache License          #
# version 2 (Apache-2.0), copied verbatim in the file "LICENSE".              #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
.build_job_minimal_matrix:
  parallel:
    matrix:
      # If you change these, don't forget to change the qualifiers in main.yaml as well.
      - LCG_QUALIFIER:
          - "cpu"
          - "cuda12_4"
          # - "hip5"

# Builds that are considered "additional", can be run in addition to "minimal" tests in certain scenarios
# This is run for each device type cpu/cuda/hip (see main.yaml)
.build_job_additional_matrix:
  parallel:
    matrix:
      # build jobs (with tests)
      - LCG_SYSTEM:
          - "x86_64_v3-el9-gcc13"
        LCG_OPTIMIZATION:
          - "opt+g"
        OPTIONS:
          - BUILD_TESTING+ENABLE_CONTRACTS+TREAT_WARNINGS_AS_ERRORS+MALLOC_ENGINE=MULTI_ALLOC

      - LCG_SYSTEM: "x86_64_v3-el9-gcc13"
        LCG_OPTIMIZATION: "dbg"
        LCG_QUALIFIER: "cuda12_4"
        OPTIONS:
          - BUILD_TESTING+ENABLE_CONTRACTS+TREAT_WARNINGS_AS_ERRORS+MALLOC_ENGINE=MULTI_ALLOC

      # # debug builds with GCC
      # - LCG_SYSTEM:
      #     - "x86_64_v3-el9-gcc13"
      #   LCG_OPTIMIZATION: dbg
      #   OPTIONS:
      #     - BUILD_TESTING+ENABLE_CONTRACTS+TREAT_WARNINGS_AS_ERRORS+MALLOC_ENGINE=MULTI_ALLOC

.build_job:
  extends: .base_job

  image: gitlab-registry.cern.ch/linuxsupport/alma9-base
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    TEST_NAME: "build"

  artifacts:
    expire_in: 1 day
    paths:
      - input
      - build*/external/ParamFiles/*
      - build*/*Allen*
      - build*/libHostCommon.so
      - build*/zmq/libAllenZMQ.so
      - build*/integration/non_event_data/libNonEventData.so
      - build*/*.json
      - build*/CTestTestfile.cmake
      - build*/test/unit_tests/unit_tests
      - build*/test/unit_tests/*cmake
      - build*/toolchain/*
      - build*/build.log
  tags:
    - cvmfs
  # retry: 2
  allow_failure:
    exit_codes: 54
