###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
#                                                                             #
# This software is distributed under the terms of the Apache License          #
# version 2 (Apache-2.0), copied verbatim in the file "LICENSE".              #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################


# Test matrices moved to scripts/ci/test_config.yaml


.run_jobs:
  extends:
    # - .base_job
    - .default_rules
  stage: "run full"
  tags: ['$DEVICE_ID']

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LCG_SYSTEM: "x86_64_v3-el9-gcc13"
    LCG_OPTIMIZATION: "opt+g"
    TEST_GROUP: "full"

  script:
    - python3 -m venv .venv && source .venv/bin/activate && pip3 install ${ALLEN_DATA}/wheels/*.whl
    - python3 scripts/ci/run_tests.py --allen-wrapper scripts/ci/allen_wrapper.sh --test-config scripts/ci/test_config.yaml --test-group ${TEST_GROUP}

  retry: 1

  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - AllenCI_full.log
      - output_*
      - run_*_output_*
      - validation_output*/*
      - run_profiler_*/
      - ./*-unit-tests.xml
    reports:
      junit:
        - ./*-unit-tests.xml
      metrics: ./**/metrics.txt

.run_jobs_minimal:
  extends:
    - .run_jobs
    # - .run_matrix_jobs_minimal
  variables:
    TEST_GROUP: "minimal"
  stage: "run"
