###############################################################################
# (c) Copyright 2018-2022 CERN for the benefit of the LHCb Collaboration      #
###############################################################################

config:
  default_timeout: 1200 # seconds
  profile_device: "a5000"

  # args added for specific test keys
  args:
    # Added to Allen command always
    base: "--params external/ParamFiles/"

    # added if "dataset:" specified
    dataset: "--mdf /scratch/allen_data/mdf_input/{dataset}.mdf"

    # added if "sequence:" specified
    sequence: "--sequence {sequence}.json"

    # added if "geometry:" specified
    geometry: "-g /scratch/allen_geometries/{geometry}"

    # added if "disable-run-changes" specified
    disable_run_changes: "--disable-run-changes {disable_run_changes}"

  # args added for specific specific test types
  test_args:
    throughput: "" # handled by target_args
    efficiency: " -n 1000 -m 1100"  # TODO incr to 10k
    run_changes: "-n 1000 -m 1000 "

  # args added for specific device targets
  target_args:
    throughput:
      pp:
        CUDA: "-n 500 -m 500 -r 1000 -t 16"
        CUDAPROF: "-n 500 -m 500 -r 1 -t 1"
        HIP: "-n 2800 --events-per-slice 2800 -m 2800 -t 10 -r 100"
        CPU: "-n 100 -m 100 -r 100"
      PbPb:
        CUDA: "-n 500 -m 3000 -r 200 -t 8 --events-per-slice 300"
        CUDAPROF: "-n 500 -m 3000 -r 1 -t 1 --events-per-slice 300"
        HIP: "-n 2800 --events-per-slice 840 -m 8400 -t 5 -r 20"
        CPU: "-n 100 -m 1000 -r 10"

# NOT GITLAB CI YAML !

minimal:
  - type: "throughput"
    sequence:
      - hlt1_pp_default
      - hlt1_pp_forward_then_matching
    dataset: "upgrade_mc_minbias_scifi_v5_retinacluster_000_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"

  - type: "efficiency"
    sequence:
      - hlt1_pp_validation
    dataset: "Upgrade_BsPhiPhi_MD_FTv4_DIGI_retinacluster_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"


  # FIXME run_changes needs re-adding
  # - type: "run_changes"
  #   sequence:
  #     - "hlt1_pp_validation"
  #   dataset: "MiniBrunel_2018_MinBias_FTv4_DIGI_retinacluster_v1_newLHCbID"
  #   disable_run_changes: ["1"] # TODO FIXME Fix disable-run-changes 0 case!!!
  #   timeout: 600
  #   allowed_devices:
  #     - epyc7502
  #     - a5000

full:
  - type: "throughput"
    sequence:
      - hlt1_pp_default
    dataset: "upgrade_mc_minbias_scifi_v5_retinacluster_000_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"
    build_options: BUILD_TESTING+ENABLE_CONTRACTS+TREAT_WARNINGS_AS_ERRORS
    throughput_report: false # don't publish throughput report

  # run throughput, no_gec
  - type: "throughput"
    sequence: 
      - hlt1_pp_SMOG2_default
    dataset: "upgrade_mc_minbias_scifi_v5_retinacluster_000_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"

  # run throughput, default, SMOG2_pppHe
  - type: "throughput"
    sequence:
      - hlt1_pp_default
      - hlt1_pp_SMOG2_default
    dataset: "SMOG2_pppHe_retinacluster_v1_newLHCbID_new_UT_geometry"
    geometry: "SMOG2_pppHe_new_UT_geometry"

  # Allen clustering jobs
  - type: "throughput"
    sequence: "hlt1_pp_veloSP"
    dataset: "upgrade_mc_minbias_scifi_v5_000_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"

  # run throughput, scifi_v6
  - type: "throughput"
    sequence:
      - hlt1_pp_default
    dataset: "SciFiv6_upgrade_DC19_01_MinBiasMD_retinacluster_v1_newLHCbID_new_UT_geometry"
    geometry: "upgrade_DC19_01_MinBiasMD_new_UT_geometry"

  # run throughput, calov4
  - type: "throughput"
    sequence: "calo"
    dataset: "sim-20190912-vc-md100-FTv7-calov4"
    geometry: "MiniBrunel_2018_MinBias_FTv4_DIGI_ecalv4"
    throughput_report: false # don't publish throughput report

  # run throughput, scifiv7
  - type: "throughput"
    sequence: "scifi_decoding"
    dataset: "SciFiV7_not_compressed"
    geometry: "MiniBrunel_2018_MinBias_FTv4_DIGI_ecalv4_scifiv7"
    throughput_report: false # don't publish throughput report

  # run throughput, muonv3
  - type: "throughput"
    sequence: "muon_decoding"
    dataset: "Run_0000232759_20220605-105749-418_MCEB02"
    geometry: "MiniBrunel_2018_MinBias_FTv4_DIGI_ecalv4_scifiv7_muonv3"
    throughput_report: false # don't publish throughput report

  # run throughput, 50% lumi events
  - type: "throughput"
    sequence:
      - hlt1_pp_lumi
    dataset: "upgrade_mc_minbias_scifi_v5_retinacluster_000_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"
    throughput_report: false # don't publish throughput report

  - type: "throughput"
    sequence:
      - hlt1_pp_default
    dataset: "upgrade-magdown-sim10-up08-30000000-digi_01_retinacluster_v1_newLHCbID_new_UT_geometry"
    geometry: "upgrade-magdown-sim10-up08-11102202-digi_new_UT_geometry"

  # run throughput, forward no ut, matching
  - type: "throughput"
    sequence:
      - hlt1_pp_matching
      - hlt1_pp_no_ut
      - hlt1_pp_forward_then_matching
      - hlt1_pp_forward_then_matching_no_ut
    dataset: "upgrade_mc_minbias_scifi_v5_retinacluster_000_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"

  # run throughput, PbPb samples, 2023 default PbPb sequence
  - type: "throughput"
    sequence:
      - hlt1_PbPb_PbSMOG_no_ut
    dataset: "upgrade-official-PbPb-EPOS-b-8_22-VELO-23.5mm"
    geometry: "geometry_dddb-20230313_sim-20230626-vc-md100"
    timeout: 2400
    collision_type: "PbPb"
    allowed_devices:
      - epyc7502
      - a5000
      - geforcertx3090

# run throughput, PbPb samples, 2023 no-gec PbPb sequence
  - type: "throughput"
    sequence:
      - hlt1_PbPb_PbSMOG_no_ut_veloSP
    dataset: "upgrade-official-PbPb-EPOS-b-8_22-VELO-23.5mm"
    geometry: "geometry_dddb-20230313_sim-20230626-vc-md100"
    timeout: 2400
    collision_type: "PbPb"
    allowed_devices:
      - epyc7502
      - a5000
      - geforcertx3090

# run throughput, PbPb samples, 2023 no-gec PbPb sequence, retina clusters
  - type: "throughput"
    sequence:
      - hlt1_PbPb_PbSMOG_no_ut_no_gec
    dataset: "upgrade-official-PbPb-EPOS-b-8_22-VELO-23.5mm"
    geometry: "geometry_dddb-20230313_sim-20230626-vc-md100"
    timeout: 2400
    collision_type: "PbPb"
    allowed_devices:
      - epyc7502
      - a5000
      - geforcertx3090

  # run throughput to assess the impact of adding downstream reconstruction
  - type: "throughput"
    sequence:
      # Impact to VeloScifi matching
      - trackmatching_veloscifi
      - trackmatching_veloscifi_and_utdecoding
      - downstream
      # Impact to full forward then matching sequence
      - hlt1_pp_forward_then_matching_and_downstream
    dataset: "upgrade_mc_minbias_scifi_v5_retinacluster_000_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"
  
# throughput test on 2024 expected sample (with beamline not at 0,0)
  - type: "throughput"
    sequence:
      - hlt1_pp_forward_then_matching_no_ut
    dataset: "Beam6800GeV-expected-2024-MagDown-nu7.6"
    geometry: "geometry_dddb-20231017_sim-20231017-vc-md100"

  # run physics efficiency for downstream reconstruction
  - type: "efficiency"
    sequence:
      - downstream_validation
      - hlt1_pp_forward_then_matching_and_downstream_validation
    dataset: "SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_retinacluster_v1_newLHCbID_v2_new_UT_geometry"
    geometry: "upgrade_DC19_01_MinBiasMD_new_UT_geometry"

  # Efficiency tests

  - type: "efficiency"
    sequence: "hlt1_pp_SMOG2_validation"
    dataset: "upgrade_mc_minbias_scifi_v5_retinacluster_000_v1_newLHCbID_new_UT_geometry"
    geometry: "geometry_dddb-20180815_sim-20180530-vc-md100_new_UT_geometry"

  - type: "run_built_tests"
    lcg_opt:
      - "opt+g"
      # - "dbg" # FIXME dbg platform not available for x86_64_v3
    build_options: "BUILD_TESTING+ENABLE_CONTRACTS+TREAT_WARNINGS_AS_ERRORS"

  # run physics efficiency, scifi_v6
  - type: "efficiency"
    sequence:
      - hlt1_pp_validation
      - hlt1_pp_no_ut_validation
      - hlt1_pp_matching_no_ut_validation
      - hlt1_pp_forward_then_matching_validation
      - hlt1_pp_forward_then_matching_no_ut_validation
    dataset: "SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_retinacluster_v1_newLHCbID_v2_new_UT_geometry"
    geometry: "upgrade_DC19_01_MinBiasMD_new_UT_geometry"

  # efficiency tests, SMOG2 pHe
  - type: "efficiency"
    sequence:
      - hlt1_pp_validation
      - hlt1_pp_SMOG2_validation
      - hlt1_pp_matching_no_ut_validation
      - hlt1_pp_forward_then_matching_validation
    dataset: "SMOG2_pHe_5k_retinacluster_v1_newLHCbID_new_UT_geometry"
    geometry: "SMOG2_pppHe_new_UT_geometry"

  - type: "efficiency"
    sequence: "hlt1_pp_veloSP_validation"
    dataset: "SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_1k_newLHCbID_new_UT_geometry"
    geometry: "upgrade_DC19_01_MinBiasMD_new_UT_geometry"

# efficiency test on 2024 expected sample (with beamline not at 0,0)
  - type: "efficiency"
    sequence:
      - hlt1_pp_forward_then_matching_no_ut_validation
    dataset: "Beam6800GeV-expected-2024-MagDown-nu7.6"
    geometry: "geometry_dddb-20231017_sim-20231017-vc-md100"