###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
#                                                                             #
# This software is distributed under the terms of the Apache License          #
# version 2 (Apache-2.0), copied verbatim in the file "LICENSE".              #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
file(GLOB velo_prefix_sum "prefix_sum/src/*cu")
file(GLOB velo_sparse_ccl_sources "sparse_ccl/src/*cu")
file(GLOB velo_retinaclusters_sources "retinacluster_decoding/src/*cu")
file(GLOB velo_search_by_triplet "search_by_triplet/src/*cu")
file(GLOB velo_simplified_kalman_filter "simplified_kalman_filter/src/*cu")
file(GLOB velo_tracks_ACsplit "tracks_ACsplit/src/*cu")
file(GLOB velo_consolidate_tracks "consolidate_tracks/src/*cu")
file(GLOB filter_for_material_interactions "filter_for_material_interactions/src/*cu")
file(GLOB quirks_filter "quirks_filter/src/*cu")


allen_add_device_library(Velo OBJECT
  ${velo_sparse_ccl_sources}
  ${velo_retinaclusters_sources}
  ${velo_prefix_sum}
  ${velo_search_by_triplet}
  ${velo_simplified_kalman_filter}
  ${velo_tracks_ACsplit}
  ${velo_consolidate_tracks}
  ${filter_for_material_interactions}
  ${quirks_filter}
)

target_link_libraries(Velo PRIVATE Backend HostEventModel EventModel Utils)

target_include_directories(Velo PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/common/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/prefix_sum/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/sparse_ccl/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/retinacluster_decoding/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/calculate_phi_and_sort/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/search_by_triplet/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/simplified_kalman_filter/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/tracks_ACsplit/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/consolidate_tracks/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/filter_for_material_interactions/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/../PV/beamlinePV/include>
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/quirks_filter/include>)

target_include_directories(WrapperInterface INTERFACE
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/common/include>)
