###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
#                                                                             #
# This software is distributed under the terms of the Apache License          #
# version 2 (Apache-2.0), copied verbatim in the file "LICENSE".              #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################


.publish_test_throughput:
  stage: publish
  extends:
    - .base_job
    - .default_rules
  variables:
    TEST_NAME: "publish_throughput"
    LCG_SYSTEM: "x86_64_v3-el9-gcc15"
    BREAKDOWN_DEVICE_ID: "a5000"
    PUBLISH_ARTIFACT_NAME: "publish_throughput"

  tags: [cvmfs]
