import os
import re
from typing import Dict, List, Tuple


def parse_header_file(
    filename: str,
) -> Dict[str, Dict[str, Dict[str, List[Tuple[float, float]]]]]:
    """Parse the C++ header file and extract all arrays."""

    with open(filename, "r") as f:
        content = f.read()

    # Pattern to match array definitions - improved to handle multi-line content
    pattern = r'resParams\["([^"]+)"\]\[Rich::([^\]]+)\]\[Rich::([^\]]+)\]\s*=\s*\{'

    data = {}
    pos = 0

    while True:
        # Find the start of an array definition
        match = re.search(pattern, content[pos:], re.DOTALL)
        if not match:
            break

        array_name, radiator, particle = match.groups()
        start_pos = pos + match.end()

        # Find the matching closing brace for this array
        brace_count = 1
        current_pos = start_pos

        while brace_count > 0 and current_pos < len(content):
            if content[current_pos] == "{":
                brace_count += 1
            elif content[current_pos] == "}":
                brace_count -= 1
            current_pos += 1

        if brace_count == 0:
            # Extract the array content (excluding the final closing brace)
            values_str = content[start_pos : current_pos - 1]

            # Parse the values
            values = []
            # Split by commas, but need to handle pairs properly
            # Find all {x, y} patterns
            pair_pattern = r"\{([^,]+),([^}]+)\}"
            pair_matches = re.findall(pair_pattern, values_str)

            for x_str, y_str in pair_matches:
                try:
                    x = float(x_str.strip())
                    y = float(y_str.strip())
                    values.append((x, y))
                except ValueError as e:
                    print(f"Error parsing pair: {{{x_str}, {y_str}}}")
                    raise e

            # Organize in nested dictionary
            if array_name not in data:
                data[array_name] = {}

            radiator_key = radiator
            if radiator_key not in data[array_name]:
                data[array_name][radiator_key] = {}

            data[array_name][radiator_key][particle] = values

            print(
                f"Parsed: {array_name} [{radiator}] [{particle}] - {len(values)} points"
            )

        # Move position for next search
        pos = current_pos

    return data


def generate_cuda_header(
    data: Dict[str, Dict[str, Dict[str, List[Tuple[float, float]]]]],
    output_filename: str,
):
    """Generate CUDA-friendly header file with transposed arrays."""

    with open(output_filename, "w") as f:
        # Write header
        f.write(
            """/*****************************************************************************\\
* (c) Copyright 2018-2026 CERN for the benefit of the LHCb Collaboration      *
*                                                                             *
* This software is distributed under the terms of the Apache License          *
* version 2 (Apache-2.0), copied verbatim in the file "LICENSE".              *
*                                                                             *
* In applying this licence, CERN does not waive the privileges and immunities *
* granted to it by virtue of its status as an Intergovernmental Organization  *
* or submit itself to any jurisdiction.                                       *
\\*****************************************************************************/
#pragma once

// NB - This file is autogenerated. Do not change by hand.
// Generated from original header file for CUDA usage.

// Converted from https://gitlab.cern.ch/lhcb/Rec/-/blob/master/Rich/RichFutureRecTrackAlgorithms/src/ResolutionParameters/Run3.h

#include <array>
#include <cstddef>
#include <MassDefinitions.h>
#include <RichTypes.cuh>

namespace Allen::Rich {
"""
        )

        # Generate constants for array sizes
        f.write("  // Array size constants\n")
        for array_name in data:
            for radiator in data[array_name]:
                for particle in data[array_name][radiator]:
                    values = data[array_name][radiator][particle]
                    const_name = f"{array_name}_{radiator}_{particle}_size"
                    f.write(f"  constexpr size_t {const_name} = {len(values)};\n")
        f.write("\n")

        # Generate device constant arrays
        for array_name in data:
            for radiator in data[array_name]:
                for particle in data[array_name][radiator]:
                    values = data[array_name][radiator][particle]

                    # Transpose the array: separate x and y values
                    x_values = [v[0] for v in values]
                    y_values = [v[1] for v in values]

                    # Write x values array
                    array_x_name = f"{array_name}_{radiator}_{particle}_x"
                    f.write(f"  __device__ constexpr float {array_x_name}[] = {{\n    ")
                    f.write(", ".join(f"{x}" for x in x_values))
                    f.write("\n  };\n\n")

                    # Write y values array
                    array_y_name = f"{array_name}_{radiator}_{particle}_y"
                    f.write(f"  __device__ constexpr float {array_y_name}[] = {{\n    ")
                    f.write(", ".join(f"{y}" for y in y_values))
                    f.write("\n  };\n\n")

            if "Momentum" in array_name:  # deal with CKAngles later
                particles = [
                    "Electron",
                    "Muon",
                    "Pion",
                    "Kaon",
                    "Proton",
                    "Proton",
                ]  # deuteron uses same param as proton
                for field in ["x", "y", "size"]:
                    array_type = "size_t" if field == "size" else "const float*"
                    f.write(
                        f"  __device__ constexpr DetectorArray<RealParticleArray<{array_type}>> "
                        f"{array_name}_{field} = {{{{{{\n"
                    )
                    f.write(
                        ",\n".join(
                            "    {\n"
                            + ",\n".join(
                                f"      {array_name}_{radiator}_{particle}_{field}"
                                for particle in particles
                            )
                            + "\n    }"
                            for radiator in data[array_name]
                        )
                    )
                    f.write("\n  }}};\n\n")

        # Close namespace
        f.write("""
} // namespace Allen::Rich
""")


def main():
    input_file = "../../../stack_rich/Rec/Rich/RichFutureRecTrackAlgorithms/src/ResolutionParameters/Run3.h"
    output_file = "../../device/event_model/rich/include/RichResolutionParams.cuh"

    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found!")
        return

    print(f"Parsing {input_file}...")
    data = parse_header_file(input_file)

    print(f"\nGenerating CUDA header {output_file}...")
    generate_cuda_header(data, output_file)

    print("Done!")
    print("\nSummary of generated arrays:")
    for array_name in data:
        print(f"\n{array_name}:")
        for radiator in data[array_name]:
            for particle in data[array_name][radiator]:
                size = len(data[array_name][radiator][particle])
                print(f"  - {radiator} / {particle}: {size} points")


if __name__ == "__main__":
    main()
